# This workflow verifies that the build passes for specified architecture on all supported OS versions.
name: Build Source

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      arch:
        required: true
        description: 'The architecture to build for'
        type: choice
        options:
          - grayskull
          - wormhole_b0
          - blackhole

env:
  BUILD_ARTEFACT_NAME: umd_device
  BUILD_OUTPUT_DIR: ./build

jobs:
  build:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        build: [
          {runs-on: ubuntu-22.04, docker_image: tt-umd-ci-ubuntu-22.04},
          {runs-on: ubuntu-20.04, docker_image: tt-umd-ci-ubuntu-20.04},
        ]

    name: Build umd_device for ${{ inputs.arch }} on ${{ matrix.build.runs-on }}
    runs-on: ${{ matrix.build.runs-on }}
    container:
      image: ghcr.io/${{ github.repository }}/${{ matrix.build.docker_image }}:latest
      options: --user root

    env:
      ARCH_NAME: ${{ inputs.arch }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build UMD
      run: |
        echo "Compiling the code..."
        cmake -B ${{ env.BUILD_OUTPUT_DIR }} -G Ninja
        cmake --build ${{ env.BUILD_OUTPUT_DIR }} --target ${{ env.BUILD_ARTEFACT_NAME }}
        echo "Compile complete."
