name: Build and Publish Docker Image

on:
  workflow_dispatch:
  workflow_call:
  push:

jobs:
  build:

    runs-on:
      - in-service
      - builder

    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: ubuntu-22.04},
          {name: ubuntu-20.04},
        ]

    env:
      CI_IMAGE_NAME:        ghcr.io/${{ github.repository }}/tt-umd-ci-${{ matrix.build.name }}

    name: Building docker image ${{ env.CI_IMAGE_NAME }}
    runs-on: ${{ matrix.build.name }}

    steps:

      - name: Fix permissions
        run: sudo chmod 777 -R $GITHUB_WORKSPACE

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build image

      - name: Build and export base Docker image
        uses: docker/build-push-action@v6
        with:
          context: .github
          file: .github/${{ matrix.build.name }}.Dockerfile
          push: true
          build-args: |
            GIT_SHA=${{ github.sha }}
          tags: |
            ${{ env.BASE_IMAGE_NAME}}:${{ github.sha }}

      # Tag image as latest

      - name: Build and push base Docker image
        uses: docker/build-push-action@v6
        with:
          context: .github
          file: .github/${{ matrix.build.name }}.Dockerfile
          push: true
          build-args: |
            GIT_SHA=${{ github.sha }}
          tags: |
            ${{ env.BASE_IMAGE_NAME}}:latest