name: Build clients on newest UMD

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  build-tt-metal:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        arch_name: [grayskull, wormhole_b0, blackhole]

    name: Build tt-metal for ${{ matrix.arch_name }} with newest UMD
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/tenstorrent/tt-metal/tt-metalium/ubuntu-20.04-amd64:latest
      options: --user root

    steps:

      - name: See status
        run: |
          echo "---1"
          pwd
          echo "---2"
          ls -la
          if [ -d "tt-metal" ]; then
            echo "---3 ls -la tt-metal"
            ls -la tt-metal
            echo "---4 ls -la tt-metal/tt_metal"
            ls -la tt-metal/tt_metal
            echo "---5 ls -la tt-metal/tt_metal/third_party/umd"
            ls -la tt-metal/tt_metal/third_party/umd
            echo "---6 ls -la tt-metal/tt_metal/third_party/umd/.github/workflows"
            ls -la tt-metal/tt_metal/third_party/umd/.github
            echo "---7 git -C tt-metal/tt_metal/third_party/umd/ status"
            git -C tt-metal/tt_metal/third_party/umd/ status
          else
            echo "Directory tt-metal does not exist."
          fi

      - name: Checkout client repo
        uses: actions/checkout@v4
        with:
          path: tt-metal
          repository: tenstorrent/tt-metal
          submodules: recursive
          lfs: 'true'

      - name: See status
        run: |
          echo "---1"
          pwd
          echo "---2"
          ls -la
          if [ -d "tt-metal" ]; then
            echo "---3 ls -la tt-metal"
            ls -la tt-metal
            echo "---4 ls -la tt-metal/tt_metal"
            ls -la tt-metal/tt_metal
            echo "---5 ls -la tt-metal/tt_metal/third_party/umd"
            ls -la tt-metal/tt_metal/third_party/umd
            echo "---6 ls -la tt-metal/tt_metal/third_party/umd/.github/workflows"
            ls -la tt-metal/tt_metal/third_party/umd/.github
            echo "---7 git -C tt-metal/tt_metal/third_party/umd/ status"
            git -C tt-metal/tt_metal/third_party/umd/ status
          else
            echo "Directory tt-metal does not exist."
          fi

      - name: Checkout UMD
        uses: actions/checkout@v4
        with:
          path: tt-metal/tt_metal/third_party/umd
          submodules: recursive
          lfs: 'true'

      - name: See status
        run: |
          echo "---1"
          pwd
          echo "---2"
          ls -la
          if [ -d "tt-metal" ]; then
            echo "---3 ls -la tt-metal"
            ls -la tt-metal
            echo "---4 ls -la tt-metal/tt_metal"
            ls -la tt-metal/tt_metal
            echo "---5 ls -la tt-metal/tt_metal/third_party/umd"
            ls -la tt-metal/tt_metal/third_party/umd
            echo "---6 ls -la tt-metal/tt_metal/third_party/umd/.github/workflows"
            ls -la tt-metal/tt_metal/third_party/umd/.github
            echo "---7 git -C tt-metal/tt_metal/third_party/umd/ status"
            git -C tt-metal/tt_metal/third_party/umd/ status
          else
            echo "Directory tt-metal does not exist."
          fi

      - name: Build tt-metal
        run: |
          pwd
          cd tt-metal
          echo "ARCH_NAME=${{ matrix.arch_name }}" >> $GITHUB_ENV
          echo "TT_METAL_HOME=$(pwd)" >> $GITHUB_ENV
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
          ./build_metal.sh
