# Build and then run all tests, on all supported archs.
name: Build and run all tests

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  build-tests:
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          {arch: grayskull},
          {arch: wormhole_b0},
          {arch: blackhole},
        ]
    uses: ./.github/workflows/build-tests.yml
    with:
      arch: ${{ matrix.test-group.arch}}
      timeout: 15

  test-all:
    secrets: inherit
    needs: build-tests
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          {arch: grayskull, card: e75, timeout: 10},
          {arch: grayskull, card: e150, timeout: 10},
          {arch: grayskull, card: e300, timeout: 10},
          {arch: wormhole_b0, card: n150, timeout: 5},
          {arch: wormhole_b0, card: n300, timeout: 15},
          # Enable once we have functional cards.
          # {arch: blackhole},
        ]
    uses: ./.github/workflows/run-tests.yml
    with:
      arch: ${{ matrix.test-group.arch}}
      card: ${{ matrix.test-group.card}}
      timeout: ${{ matrix.test-group.timeout}}
