# Runs yamllint on all yaml files in the github workflows directory
name: Build Target

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {runs-on: ubuntu-22.04, docker-image: tt-umd-ci-ubuntu-22.04},
          {runs-on: ubuntu-20.04, docker-image: tt-umd-ci-ubuntu-20.04},
        ]

    name: Run yamllint
    # It is unnecessary to run this job on multiple OS versions
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/${{ github.repository }}/tt-umd-ci-ubuntu-22.04:latest
      options: --user root

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run yamllint
        run: yamllint .github/workflows/*