name: On Push

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build-all:
    secrets: inherit
    uses: ./.github/workflows/build-device.yml
    with:
      timeout: 15

  build-tests:
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          # Enable once we have functional cards with specified architecture.
          {arch: grayskull},
          {arch: wormhole_b0},
          # {arch: blackhole},
        ]
    uses: ./.github/workflows/build-tests.yml
    with:
      arch: ${{ matrix.test-group.arch }}
      timeout: 15

  test-all:
    secrets: inherit
    needs: build-tests
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          # Enable once we have functional cards.
          {arch: grayskull, card: e75, timeout: 10},
          {arch: grayskull, card: e150, timeout: 10},
          {arch: grayskull, card: e300, timeout: 10},
          {arch: wormhole_b0, card: n150, timeout: 5},
          {arch: wormhole_b0, card: n300, timeout: 15},
          # {arch: blackhole},
        ]
    uses: ./.github/workflows/run-tests.yml
    with:
      arch: ${{ matrix.test-group.arch }}
      card: ${{ matrix.test-group.card }}
      timeout: ${{ matrix.test-group.timeout }}

  pre-commit:
    name: Run Pre-commit Hooks and Propose Fixes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history so 'origin/main' is available
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run Pre-commit and Fix Issues
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: "--from-ref origin/main --to-ref HEAD"
