# Mandatory PR checks
name: On PR

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:
  lint-yaml:
    secrets: inherit
    uses: ./.github/workflows/lint-yaml.yml

  build-all:
    secrets: inherit
    uses: ./.github/workflows/build-device.yml
    with:
      timeout: 10

  pre-commit:
    name: Run Pre-commit Hooks and Propose Fixes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history so 'origin/main' is available
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run Pre-commit and Fix Issues
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: "--from-ref origin/main --to-ref HEAD"
        continue-on-error: true

      - name: Check for Modified Files and Set Flag
        id: git_diff
        run: |
          git diff --exit-code || echo "::set-output name=changes-detected::true"

      - name: Create Pull Request with Fixes
        if: steps.git_diff.outputs.changes-detected == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Fix pre-commit issues"
          title: "Propose pre-commit fixes"
          body: "This PR contains proposed fixes from pre-commit hooks."

      - name: Fail the Job if Changes Were Made
        if: steps.git_diff.outputs.changes-detected == 'true'
        run: |
          echo "Pre-commit made changes. Marking job as failed."
          exit 1  # Fail the job explicitly if changes were made
