name: On Push

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build-all:
    secrets: inherit
    uses: ./.github/workflows/build-device.yml
    with:
      timeout: 15

  pre-commit:
    secrets: inherit
    uses: ./.github/workflows/pre-commit.yml

  build-tests:
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          # Enable once we have functional cards with specified architecture.
          {arch: grayskull},
          {arch: wormhole_b0},
          # {arch: blackhole},
        ]
    uses: ./.github/workflows/build-tests.yml
    with:
      arch: ${{ matrix.test-group.arch }}
      timeout: 15

  test-all:
    secrets: inherit
    needs: build-tests
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          # Enable once we have functional cards.
          {arch: grayskull, card: e75, timeout: 10},
          {arch: grayskull, card: e150, timeout: 10},
          {arch: grayskull, card: e300, timeout: 10},
          {arch: wormhole_b0, card: n150, timeout: 5},
          {arch: wormhole_b0, card: n300, timeout: 15},
          # {arch: blackhole},
        ]
    uses: ./.github/workflows/run-tests.yml
    with:
      arch: ${{ matrix.test-group.arch }}
      card: ${{ matrix.test-group.card }}
      timeout: ${{ matrix.test-group.timeout }}
