# Optional PR checks
name: On PR - Optional

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build-tests:
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          # { arch: grayskull },
          { arch: wormhole_b0 },
          # { arch: blackhole },
        ]
    uses: ./.github/workflows/build-tests.yml
    with:
      arch: ${{ matrix.test-group.arch }}

  test-all:
    secrets: inherit
    needs: build-tests
    strategy:
      fail-fast: false
      matrix:
        test-group: [
          # { arch: grayskull, card: e75 },
          # { arch: grayskull, card: e150 },
          # { arch: grayskull, card: e300 },
          { arch: wormhole_b0, card: n150 },
          { arch: wormhole_b0, card: n300 },
          # { arch: blackhole },
        ]
    uses: ./.github/workflows/run-tests.yml
    with:
      arch: ${{ matrix.test-group.arch }}
      card: ${{ matrix.test-group.card }}